### ISSUE TITLE
mb makehashes -b /srv/ftp/pub/opensuse -t /srv/metalink-hashes/srv/ftp/pub/opensuse throws db error

### ISSUE THREAD

**Issue by lkocman** [openSUSE/publish_distro#9]
This is an output with set -x

```
mirror@pontifex2:~/publish_distro> ./publish_distro_leap153 publish_leap153.config 
+ PUBLISH_DELAY=2
+ force=
+ date=now
+ dryrun=
+ do_cleanup=
+ diff_url_base=https://openqa.opensuse.org/snapshot-changes/opensuse
+ changes_dir_base=/srv/www-local/snapshot-changes
+ repos=("oss" "non-oss")
+ extra_repos=("source" "debug")
+ isodir=iso
+ for arg in "$@"
+ shift
+ '[' publish_leap153.config == --force ']'
+ '[' publish_leap153.config == --dry ']'
+ '[' publish_leap153.config == --cleanup ']'
+ newargs+=("$arg")
+ set -- publish_leap153.config
+ . publish_leap153.config
++ leap_version=15.3
+++ date -d now +%Y/%m/%d/%H%M
++ logfile_base=/home/mirror/publish_logs/15.3/2021/02/03/1415
++ synclog=/home/mirror/publish_logs/15.3/2021/02/03/1415.log
++ deletelog=/home/mirror/publish_logs/15.3/2021/02/03/1415-deletes.log
++ path=/distribution/leap/15.3
++ flavors=(DVD-x86_64 NET-x86_64 DVD-aarch64 NET-aarch64 DVD-ppc64le NET-ppc64le DVD-s390x NET-s390x)
+ shift
+ stage=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3
+ dest=/srv/ftp/pub/opensuse//distribution/leap/15.3
+ '[' '!' -e /srv/ftp-stage/pub/opensuse//distribution/leap/15.3 -o '!' -e /srv/ftp/pub/opensuse//distribution/leap/15.3 ']'
+ '[' -n '' ']'
+ mkdir -p /home/mirror/publish_logs/15.3/2021/02/03 /home/mirror/publish_logs/15.3/2021/02/03
+ test -f /home/mirror/publish_logs/15.3/2021/02/03/1415.log
+ test -f /home/mirror/publish_logs/15.3/2021/02/03/1415-deletes.log
+ version=
+ do_sync_isos=1
+ for flavor in "${flavors[@]}"
+ get_version
+ '[' -z '' ']'
++ echo /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/iso/openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso
+ version=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/iso/openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso
+ version=65.8-Media.iso
+ version=65.8
+ '[' -z 65.8 ']'
+ get_iso
+ iso=openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso
+ get_diff_url
+ url=https://openqa.opensuse.org/snapshot-changes/opensuse/15.3/diff/65.8
+ get_changes_filename
+ :
+ '[' -z '' -a -e /srv/ftp/pub/opensuse//distribution/leap/15.3/iso/openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso ']'
+ '[' -t 1 ']'
+ echo 'openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso already published, skipping isos'
openSUSE-Leap-15.3-DVD-x86_64-Build65.8-Media.iso already published, skipping isos
+ do_sync_isos=0
+ break
+ for r in "${repos[@]/#//repo/}"
+ for i in /suse/setup /boot
+ d=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/suse/setup
+ '[' -d /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/suse/setup ']'
+ continue
+ for i in /suse/setup /boot
+ d=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/boot
+ '[' -d /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/boot ']'
+ '[' -e /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/media.1/build ']'
+ '[' -e /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/media.1/media ']'
+ read dummy
+ read build
+ stamp=65.8
+ '[' openSUSE-Leap-15.3-x86_64-aarch64-ppc64le-s390x-Build65.8 = 65.8 ']'
+ stamped=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/65.8-boot
+ '[' '!' -L /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/oss/boot ']'
+ for r in "${repos[@]/#//repo/}"
+ for i in /suse/setup /boot
+ d=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/suse/setup
+ '[' -d /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/suse/setup ']'
+ continue
+ for i in /suse/setup /boot
+ d=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/boot
+ '[' -d /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/boot ']'
+ '[' -e /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/media.1/build ']'
+ '[' -e /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/media.1/media ']'
+ read dummy
+ read build
+ stamp=65.8
+ '[' openSUSE-Leap-15.3-Addon-NonOss-FTP-x86_64-aarch64-ppc64le-s390x-Build65.8 = 65.8 ']'
+ stamped=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/65.8-boot
+ '[' '!' -L /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo/non-oss/boot ']'
+ do_sync_isos=1
+ '[' 1 = 0 ']'
+ TODO=()
+ TODO+=(iso)
+ echo 'current 65.8'
+ tee /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/iso/.current.txt
current 65.8
+ '[' -n oss ']'
+ TODO+=(repo)
+ TODO+=(DELETE_repo)
+ for i in "${TODO[@]}"
+ case $i in
+ log=/home/mirror/publish_logs/15.3/2021/02/03/1415.log
+ dry_delete=--delete-after
+ i=iso
+ echo ========== iso --delete-after ===========
========== iso --delete-after ===========
+ rsync -avvhiH /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/iso --link-dest=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3 /srv/ftp/pub/opensuse//distribution/leap/15.3 --delete-after
+ LC_ALL=C
+ grep -v '^\.[fdL]      '
+ LC_ALL=C
+ grep -v '^\(sending\|delta\)'
+ tee -a /home/mirror/publish_logs/15.3/2021/02/03/1415.log
building file list ... done
total: matches=0  hash_hits=0  false_alarms=0 data=0
deleting in iso

sent 4.39K bytes  received 280 bytes  9.35K bytes/sec
total size is 15.66G  speedup is 3,349,027.71
+ for i in "${TODO[@]}"
+ case $i in
+ log=/home/mirror/publish_logs/15.3/2021/02/03/1415.log
+ dry_delete=
+ echo ========== repo ===========
========== repo ===========
+ rsync -avvhiH /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo --link-dest=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3 /srv/ftp/pub/opensuse//distribution/leap/15.3
+ LC_ALL=C
+ grep -v '^\.[fdL]      '
+ tee -a /home/mirror/publish_logs/15.3/2021/02/03/1415.log
+ LC_ALL=C
+ grep -v '^\(sending\|delta\)'
.d..t...... repo/non-oss/
.d..t...... repo/non-oss/aarch64/
.d..t...... repo/non-oss/noarch/
.d..t...... repo/non-oss/ppc64le/
.d..t...... repo/non-oss/repodata/
.d..t...... repo/non-oss/s390x/
.d..t...... repo/non-oss/x86_64/
.d..t...... repo/oss/
.d..t...... repo/oss/aarch64/
.d..t...... repo/oss/noarch/
.d..t...... repo/oss/ppc64le/
.d..t...... repo/oss/repodata/
.d..t...... repo/oss/s390x/
.d..t...... repo/oss/x86_64/
total: matches=0  hash_hits=0  false_alarms=0 data=0

sent 4.93M bytes  received 287.85K bytes  1.16M bytes/sec
total size is 124.47G  speedup is 23,835.89
+ for i in "${TODO[@]}"
+ case $i in
+ i=repo
+ log=/home/mirror/publish_logs/15.3/2021/02/03/1415-deletes.log
+ dry_delete='--delete -n'
+ echo ========== repo --delete -n ===========
========== repo --delete -n ===========
+ rsync -avvhiH /srv/ftp-stage/pub/opensuse//distribution/leap/15.3/repo --link-dest=/srv/ftp-stage/pub/opensuse//distribution/leap/15.3 /srv/ftp/pub/opensuse//distribution/leap/15.3 --delete -n
+ LC_ALL=C
+ grep -v '^\(sending\|delta\)'
+ tee -a /home/mirror/publish_logs/15.3/2021/02/03/1415-deletes.log
+ LC_ALL=C
+ grep -v '^\.[fdL]      '
total: matches=0  hash_hits=0  false_alarms=0 data=0

sent 4.93M bytes  received 287.85K bytes  1.49M bytes/sec
total size is 124.47G  speedup is 23,835.89 (DRY RUN)
+ for r in "${extra_repos[@]}"
+ stage=/srv/ftp-stage/pub/opensuse/source//distribution/leap/15.3
+ dest=/srv/ftp/pub/opensuse/source//distribution/leap/15.3
+ rsync -avhiH /srv/ftp-stage/pub/opensuse/source//distribution/leap/15.3/ --link-dest=/srv/ftp-stage/pub/opensuse/source//distribution/leap/15.3 /srv/ftp/pub/opensuse/source//distribution/leap/15.3 --delete-after
+ tee -a log
building file list ... done

sent 59 bytes  received 11 bytes  140.00 bytes/sec
total size is 0  speedup is 0.00
+ for r in "${extra_repos[@]}"
+ stage=/srv/ftp-stage/pub/opensuse/debug//distribution/leap/15.3
+ dest=/srv/ftp/pub/opensuse/debug//distribution/leap/15.3
+ rsync -avhiH /srv/ftp-stage/pub/opensuse/debug//distribution/leap/15.3/ --link-dest=/srv/ftp-stage/pub/opensuse/debug//distribution/leap/15.3 /srv/ftp/pub/opensuse/debug//distribution/leap/15.3 --delete-after
+ tee -a log
building file list ... done

sent 104 bytes  received 11 bytes  230.00 bytes/sec
total size is 0  speedup is 0.00
+ get_mark_published_url
+ url=https://openqa.opensuse.org/snapshot-changes/opensuse/15.3/current
+ '[' -n https://openqa.opensuse.org/snapshot-changes/opensuse/15.3/current ']'
+ curl -X POST -F version=65.8 https://openqa.opensuse.org/snapshot-changes/opensuse/15.3/current
curl: (6) Could not resolve host: openqa.opensuse.org
+ echo creating hashes
creating hashes
+ /usr/bin/mb makehashes -b /srv/ftp/pub/opensuse -t /srv/metalink-hashes/srv/ftp/pub/opensuse /srv/ftp/pub/opensuse/debug//distribution/leap/15.3
Traceback (most recent call last):
  File "/usr/bin/mb", line 1729, in <module>
    r = mirrordoctor.main()
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/bin/mb", line 1056, in do_makehashes
    for i, j in mb.files.dir_filelist(self.conn, dst_dir_db)]
  File "/usr/lib64/python2.7/site-packages/mb/files.py", line 162, in dir_filelist
    result = conn.Server._connection.queryAll(query)
  File "/usr/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 449, in queryAll
    return self._runWithConnection(self._queryAll, s)
  File "/usr/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "/usr/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 441, in _queryAll
    self._executeRetry(conn, c, s)
  File "/usr/lib/python2.7/site-packages/sqlobject/postgres/pgconnection.py", line 257, in _executeRetry
    raise dberrors.ProgrammingError(msg)
sqlobject.dberrors.ProgrammingError: column filearr.dirname does not exist
LINE 5:                WHERE filearr.dirname = '\\144\\145\\142\\165...
                             ^


```

**Comment by lkocman** [comment]
This happens every time
